apiVersion: v1
kind: Service
metadata:
  name: git-daemon
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: git-daemon
  ports:
    - name: git
      protocol: TCP
      port: 9418
      targetPort: 9418
